[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "viser"
version = "0.1.10"
description = "3D visualization + Python"
readme = "README.md"
license = { text="MIT" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "websockets>=10.4",
    "numpy>=1.0.0",
    "msgpack>=1.0.0",
    "imageio>=2.0.0",
    "pyliblzfse>=0.4.1",
    "scikit-image>=0.18.0",
    "scipy>=1.7.3",
    "tqdm>=4.0.0",
    "tyro>=0.2.0",
    "gdown>=4.6.6",
    "rich>=13.3.3",
    "trimesh>=3.21.7",
    "nodeenv>=1.8.0",
    "psutil>=5.9.5",
    "yourdfpy>=0.0.53",
]

[project.optional-dependencies]
dev = [
    "pyright>=1.1.308",
    "mypy>=1.4.1",
    "ruff==0.0.267",
    "black==23.3.0",
    "pre-commit==3.3.2",
]
examples = [
    "smplx>=0.1.28",
    "torch>=1.13.1",
    "matplotlib>=3.7.1",
]

[project.urls]
"GitHub" = "https://github.com/nerfstudio-project/viser"

[tool.setuptools.package-data]
viser = ["py.typed", "_icons/tabler-icons.tar", "client/build/**/*"]

[project.scripts]
viser-dev-checks = "viser.scripts.dev_checks:entrypoint"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true
warn_unused_configs = true
exclude="viser/client/.nodeenv"
disable_error_code="var-annotated"  # Common source of mypy + numpy false positives.

[tool.pyright]
exclude = ["./docs/**/*", "./examples/assets/**/*", "./src/viser/client/.nodeenv", "./build"]

[tool.black]
exclude = "viser/client/.nodeenv"

[tool.ruff]
select = [
    "E",  # pycodestyle errors.
    "F",  # Pyflakes rules.
    "PLC",  # Pylint convention warnings.
    "PLE",  # Pylint errors.
    "PLR",  # Pylint refactor recommendations.
    "PLW",  # Pylint warnings.
]
ignore = [
    "E741", # Ambiguous variable name. (l, O, or I)
    "E501",  # Line too long.
    "F722",  # Forward annotation false positive from jaxtyping. Should be caught by pyright.
    "F821",  # Forward annotation false positive from jaxtyping. Should be caught by pyright.
    "PLR2004",  # Magic value used in comparison.
    "PLR0915",  # Too many statements.
    "PLR0913",  # Too many arguments.
    "PLC0414",  # Import alias does not rename variable. (this is used for exporting names)
    "PLC1901",  # Use falsey strings.
    "PLR5501",  # Use `elif` instead of `else if`.
    "PLR0911",  # Too many return statements.
    "PLR0912",  # Too many branches.
    "PLW0603",  # Globa statement updates are discouraged.
    "PLW2901",  # For loop variable overwritten.
]
exclude = [ ".nodeenv" ]
